name: Init-Env-Vars
description: 'Initialize environment variables'
inputs:
  registry_fqdn:
    description: 'The fully qualified domain name of the registry'
    required: true
outputs:
  output_get_pwd:
    value: ${{ steps.get-pwd.outputs.curdir }}
  output_get_cpu_info:
    value: ${{ steps.get-cpu-info.outputs.NB_CORES }}
  output_get_distro_tag:
    value: ${{ steps.compose-image-tag.outputs.EE_Distro_tag }}
  # output_build_dir:
  #   value: ${{ steps.ccache-folder.outputs.BUILD_DIR }}
  # output_ccache_folder:
  #   value: ${{ steps.ccache-folder.outputs.CCACHE_DIR }}
runs:
  using: "composite"
  steps:
    - name: Set BUILDER_VERSION
      id: set-builder-version
      shell: bash
      run: echo "BUILDER_VERSION=13.0-$(date +%Y%m%d)" | sudo tee -a $GITHUB_OUTPUT

    - name: Get current directory
      id: get-pwd
      shell: bash
      run: echo "curdir=$PWD" | sudo tee -a $GITHUB_OUTPUT

    - name: Get Date
      id: get-date
      shell: bash
      run: |
        # echo "[date]: $(/bin/date -u "+%Y%m%d")"
        echo "date=$(/bin/date -u "+%Y%m%d")" | sudo tee -a $GITHUB_OUTPUT

    - name: Get CPU info
      id: get-cpu-info
      shell: bash
      run: echo "NB_CORES=$(grep -c '^processor' /proc/cpuinfo)" | sudo tee -a $GITHUB_OUTPUT

    - name: Set DistroCodeName
      id: set-distro-codename
      shell: bash
      run: echo "DistroCodeName=${{ env.DistroCodeName }} | sudo tee -a $GITHUB_OUTPUT

    -
      name: Compose image tag
      id: compose-image-tag
      shell: bash
      run: |
        dTag="${{ inputs.registry_fqdn }}/${{ github.repository_owner }}/${{ env.DistroCodeName }}"
        # Use ,, to convert all characters to lowercase
        echo "EE_Distro_tag=${dTag,,}" | sudo tee -a $GITHUB_OUTPUT

    # - name: Determine .ccache folder location
    #   id: ccache-folder
    #   shell: bash
    #   run: |
    #     BUILD_DIR=/build/build.${{ env.EE_Distro }}-${{ env.EE_Device }}.${{ env.EE_Arch }}-13.0-devel
    #     CCACHE_DIR=$BUILD_DIR/.ccache
    #     echo "BUILD_DIR=$BUILD_DIR" | sudo tee -a $GITHUB_OUTPUT
    #     echo "CCACHE_DIR=$CCACHE_DIR" | sudo tee -a $GITHUB_OUTPUT
    #     # if [ "${DISTRO_VERSION}" = "devel" ] ; then
    #     #   BUILD=/build.${{ env.EE_Distro }}-${{ env.EE_Distro }}.${{ env.EE_Arch }}-13.0-${DISTRO_VERSION}
    #     # else
    #     #   BUILD=/build.${{ env.EE_Distro }}-${{ env.EE_Distro }}.${{ env.EE_Arch }}-${DISTRO_VERSION}
    #     # fi
