name: Init-Env-Vars
description: 'Initialize environment variables'
inputs:
  gh-token:
    description: 'A Github PAT'
    required: true
outputs:
  output_get_pwd:
    value: ${{ steps.get-pwd.outputs.curdir }}
  output_get_cpu_info:
    value: ${{ steps.get-cpu-info.outputs.NB_CORES }}
  output_build_dir:
    value: ${{ steps.ccache-folder.outputs.BUILD_DIR }}
  output_ccache_folder:
    value: ${{ steps.ccache-folder.outputs.CCACHE_DIR }}
runs:
  using: "composite"
  steps:
    - name: Set BUILDER_VERSION
      id: set-builder-version
      shell: bash
      # env:
      #   GH_TOKEN: ${{ inputs.gh-token }}
      run: echo "BUILDER_VERSION=13.0-$(date +%Y%m%d)" | sudo tee -a $GITHUB_OUTPUT

    - name: Get current directory
      id: get-pwd
      shell: bash
      # env:
      #   GH_TOKEN: ${{ inputs.gh-token }}
      run: echo "curdir=$PWD" | sudo tee -a $GITHUB_OUTPUT

    - name: Get Date
      id: get-date
      shell: bash
      # env:
      #   GH_TOKEN: ${{ inputs.gh-token }}
      run: |
        # echo "[date]: $(/bin/date -u "+%Y%m%d")"
        echo "date=$(/bin/date -u "+%Y%m%d")" | sudo tee -a $GITHUB_OUTPUT

    - name: Get CPU info
      id: get-cpu-info
      shell: bash
      # env:
      #   GH_TOKEN: ${{ inputs.gh-token }}
      run: echo "NB_CORES=$(grep -c '^processor' /proc/cpuinfo)" | sudo tee -a $GITHUB_OUTPUT

    - name: Determine .ccache folder location
      id: ccache-folder
      shell: bash
      # env:
      #   GH_TOKEN: ${{ inputs.gh-token }}
      run: |
        BUILD_DIR=/build/build.${{ env.EE_Distro }}-${{ env.EE_Device }}.${{ env.EE_Arch }}-13.0-devel
        CCACHE_DIR=$BUILD_DIR/.ccache
        echo "BUILD_DIR=$BUILD_DIR" | sudo tee -a $GITHUB_OUTPUT
        echo "CCACHE_DIR=$CCACHE_DIR" | sudo tee -a $GITHUB_OUTPUT
        # if [ "${DISTRO_VERSION}" = "devel" ] ; then
        #   BUILD=/build.${{ env.EE_Distro }}-${{ env.EE_Distro }}.${{ env.EE_Arch }}-13.0-${DISTRO_VERSION}
        # else
        #   BUILD=/build.${{ env.EE_Distro }}-${{ env.EE_Distro }}.${{ env.EE_Arch }}-${DISTRO_VERSION}
        # fi
