# Azure Pipelines conversion of .github/workflows/build-docker-image.yml
# - Trigger: push to `master-entw`
# - Parameters: `runner` and `environment` (same choices as GH Action)
# - Notes:
#   Recommended: use an Azure Container Registry (ACR) service connection.
#   - Set the pipeline variable `ACR_SERVICE_CONNECTION` to the name of the service connection.
#   Legacy: username/password variables are still supported but not recommended.

trigger:
  branches:
    include:
      - master-entw

pr: none

parameters:
  - name: runner
    displayName: Runner
    type: string
    default: github
    values:
      - github
      - self-hosted
      - gitea
  - name: environment
    displayName: Environment
    type: string
    default: noble
    values:
      - bookworm
      - jammy
      - noble
      - noble-custom
      - plucky
      - questing
      - sid

variables:
  RUNNER_TOOL_CACHE: /toolcache
  BUILDKIT_PROGRESS: 'auto'
  # Name of an ACR service connection (set this in the pipeline UI)
  ACR_SERVICE_CONNECTION: 'eddict-acr-connection'

jobs:
- job: Build
  displayName: Build and push Docker image
  pool:
    ${{ if eq(parameters.runner, 'self-hosted') }}:
      name: 'Self-Hosted'
    ${{ if ne(parameters.runner, 'self-hosted') }}:
      vmImage: 'ubuntu-latest'

  steps:
  - bash: |
      echo "## Get docker guid and set pipeline variable"
      DGUID=$(id -u docker 2>/dev/null || echo "0")
      echo "docker-guid=${DGUID}"
      echo "##vso[task.setvariable variable=docker_guid]${DGUID}"
    displayName: Get docker guid

  - bash: |
      echo "## Compose image tag based on runner and environment"
      # Choose registry based on runner parameter (used only for display; ACR service connection will control push)
      if [ "${{ parameters.runner }}" = "github" ]; then
        REGISTRY=ghcr.io
      elif [ "${{ parameters.runner }}" = "gitea" ]; then
        REGISTRY=${MYGITEA_REGISTRY_FQDN}
      else
        REGISTRY=ghcr.io
      fi

      # Build repository name: Azure provides BUILD_REPOSITORY_NAME
      REPO_NAME=${BUILD_REPOSITORY_NAME}

      IMAGE_REPO="${REPO_NAME}-${{ parameters.environment }}"
      EE_Distro_tag="${REGISTRY}/${IMAGE_REPO}"
      EE_Distro_tag_lower=$(echo "${EE_Distro_tag}:latest" | tr '[:upper:]' '[:lower:]')

      echo "IMAGE_REPO=${IMAGE_REPO}"
      echo "EE_Distro_tag=${EE_Distro_tag_lower}"
      echo "##vso[task.setvariable variable=IMAGE_REPO]${IMAGE_REPO}"
      echo "##vso[task.setvariable variable=EE_Distro_tag]${EE_Distro_tag_lower}"
      echo "##vso[task.setvariable variable=REGISTRY]${REGISTRY}"
    displayName: Compose image tag
    env:
      MYGITEA_REGISTRY_FQDN: $(MYGITEA_REGISTRY_FQDN)

  - bash: |
      echo "## Registry selection: prefer ACR service connection"
      if [ -n "$(ACR_SERVICE_CONNECTION)" ]; then
        echo "ACR service connection is set: $(ACR_SERVICE_CONNECTION)"
      else
        echo "No ACR service connection set; pipeline will attempt legacy docker login using pipeline secrets."
      fi
    displayName: Registry selection

  - bash: |
      echo "## Prepare build (Docker@2 will perform build/push when using ACR service connection)"
    displayName: Prepare build
  - bash: |
      echo "## Verify ACR service connection is set"
      if [ -z "$ACR_SERVICE_CONNECTION" ]; then
        echo "ERROR: ACR_SERVICE_CONNECTION pipeline variable is empty."
        echo "Create an Azure Container Registry service connection and set the pipeline variable 'ACR_SERVICE_CONNECTION' to its name."
        echo "See project settings -> Service connections in Azure DevOps, or set the variable in the pipeline YAML."
        exit 1
      fi
      echo "Using ACR service connection: $ACR_SERVICE_CONNECTION"
    displayName: Require ACR service connection

  - task: Docker@2
    displayName: Build and push (ACR service connection)
    inputs:
      containerRegistry: '$(ACR_SERVICE_CONNECTION)'
      command: buildAndPush
      Dockerfile: 'tools/docker/${{ parameters.environment }}/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      repository: '$(IMAGE_REPO)'
      tags: 'latest'
      arguments: >-
        --label org.opencontainers.image.source=https://github.com/Eddict/EddictwareELEC
        --label org.opencontainers.image.ref.name=$(EE_Distro_tag)
        --build-arg USER_UID=$(docker_guid)

  - bash: |
      echo "## Attestation placeholder"
      echo "Subject: ${EE_Distro_tag}"
      # In GitHub Actions the actions/attest-build-provenance is used. You can integrate Cosign or other attestation tooling here.
    displayName: Generate artifact attestation (placeholder)

  - bash: |
      echo "Done. The image was built and pushed to: ${EE_Distro_tag}:latest"
    displayName: Done

# Usage notes:
# - Create pipeline variables (in UI or variable group) for secrets:
#   - REGISTRY_PWD (secret)
#   - REGISTRY_USER
#   - MYGITEA_REGISTRY_FQDN
#   - MYGITEA_REGISTRY_USER
#   - MYGITEA_REGISTRY_TOKEN (secret)
#   - Optionally provide GITHUB_TOKEN and GITHUB_ACTOR if you want GH-specific login behavior
# - To run manually, choose parameters `runner` and `environment` in the Run pipeline dialog.
