# Azure Pipelines conversion of .github/workflows/build-docker-image.yml
# - Trigger: push to `master-entw`
# - Parameters: `runner` and `environment` (same choices as GH Action)
# - Notes: supply registry secrets as pipeline variables or variable groups:
#   - REGISTRY_PWD, REGISTRY_USER, MYGITEA_REGISTRY_FQDN, MYGITEA_REGISTRY_USER, MYGITEA_REGISTRY_TOKEN
#   - Mark secrets as secret in the pipeline UI

trigger:
  branches:
    include:
      - master-entw

pr: none

parameters:
  - name: runner
    displayName: Runner
    type: string
    default: github
    values:
      - github
      - self-hosted
      - gitea
  - name: environment
    displayName: Environment
    type: string
    default: noble
    values:
      - bookworm
      - jammy
      - noble
      - noble-custom
      - plucky
      - questing
      - sid

variables:
  RUNNER_TOOL_CACHE: /toolcache
  BUILDKIT_PROGRESS: 'auto'

jobs:
- job: Build
  displayName: Build and push Docker image
  pool:
    ${{ if eq(parameters.runner, 'self-hosted') }}:
      name: 'Self-Hosted'
    ${{ if ne(parameters.runner, 'self-hosted') }}:
      vmImage: 'ubuntu-latest'

  steps:
  - bash: |
      echo "## Get docker guid and set pipeline variable"
      DGUID=$(id -u docker 2>/dev/null || echo "0")
      echo "docker-guid=${DGUID}"
      echo "##vso[task.setvariable variable=docker_guid]${DGUID}"
    displayName: Get docker guid

  - bash: |
      echo "## Compose image tag based on runner and environment"
      # Choose registry based on runner parameter
      if [ "${{ parameters.runner }}" = "github" ]; then
        REGISTRY=ghcr.io
      elif [ "${{ parameters.runner }}" = "gitea" ]; then
        REGISTRY=${MYGITEA_REGISTRY_FQDN}
      else
        REGISTRY=ghcr.io
      fi

      # Build repository name: Azure provides BUILD_REPOSITORY_NAME
      REPO_NAME=${BUILD_REPOSITORY_NAME}

      EE_Distro_tag="${REGISTRY}/${REPO_NAME}-${{ parameters.environment }}"
      EE_Distro_tag_lower=$(echo "$EE_Distro_tag" | tr '[:upper:]' '[:lower:]')

      echo "EE_Distro_tag=${EE_Distro_tag_lower}"
      echo "##vso[task.setvariable variable=EE_Distro_tag]${EE_Distro_tag_lower}"
      echo "##vso[task.setvariable variable=REGISTRY]${REGISTRY}"
    displayName: Compose image tag
    env:
      MYGITEA_REGISTRY_FQDN: $(MYGITEA_REGISTRY_FQDN)

  - bash: |
      echo "## Log in to registry using provided secrets (set these in pipeline variables/variable groups)"
      REGISTRY=${REGISTRY:-$(echo ${EE_Distro_tag} | cut -d'/' -f1)}

      if [ "${{ parameters.runner }}" = "github" ]; then
        USERNAME=${GITHUB_ACTOR:-$REGISTRY_USER}
        PASSWORD=${GITHUB_TOKEN:-$REGISTRY_PWD}
      elif [ "${{ parameters.runner }}" = "gitea" ]; then
        USERNAME=${MYGITEA_REGISTRY_USER}
        PASSWORD=${MYGITEA_REGISTRY_TOKEN}
      else
        USERNAME=${REGISTRY_USER}
        PASSWORD=${REGISTRY_PWD}
      fi

      if [ -z "$PASSWORD" ]; then
        echo "WARNING: registry password is empty. Please set REGISTRY_PWD or relevant secret."
      fi

      echo "Logging into ${REGISTRY} as ${USERNAME}"
      echo "$PASSWORD" | docker login ${REGISTRY} -u "$USERNAME" --password-stdin
    displayName: Log in to registry
    env:
      REGISTRY_USER: $(REGISTRY_USER)
      REGISTRY_PWD: $(REGISTRY_PWD)
      MYGITEA_REGISTRY_USER: $(MYGITEA_REGISTRY_USER)
      MYGITEA_REGISTRY_TOKEN: $(MYGITEA_REGISTRY_TOKEN)
      GITHUB_ACTOR: $(GITHUB_ACTOR)
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - bash: |
      echo "## Ensure buildx is available and create a builder"
      docker buildx version || true
      docker buildx create --use --name builder-eddictwareelec || true
      docker buildx inspect --bootstrap
    displayName: Set up Docker Buildx

  - bash: |
      echo "## Build and push image with buildx"
      DOCKERFILE=./tools/docker/${{ parameters.environment }}/Dockerfile
      if [ ! -f "$DOCKERFILE" ]; then
        echo "ERROR: Dockerfile $DOCKERFILE not found"
        exit 1
      fi

      TAG=$(echo "${EE_Distro_tag}:latest")

      docker buildx build \
        --file "$DOCKERFILE" \
        --tag "$TAG" \
        --label "org.opencontainers.image.source=https://github.com/Eddict/EddictwareELEC" \
        --label "org.opencontainers.image.ref.name=${EE_Distro_tag}" \
        --build-arg USER_UID=${docker_guid} \
        --push \
        "$PWD"

      echo "Pushed $TAG"
    displayName: Build and export to registry

  - bash: |
      echo "## Attestation placeholder"
      echo "Subject: ${EE_Distro_tag}"
      # In GitHub Actions the actions/attest-build-provenance is used. You can integrate Cosign or other attestation tooling here.
    displayName: Generate artifact attestation (placeholder)

  - bash: |
      echo "Done. The image was built and pushed to: ${EE_Distro_tag}:latest"
    displayName: Done

# Usage notes:
# - Create pipeline variables (in UI or variable group) for secrets:
#   - REGISTRY_PWD (secret)
#   - REGISTRY_USER
#   - MYGITEA_REGISTRY_FQDN
#   - MYGITEA_REGISTRY_USER
#   - MYGITEA_REGISTRY_TOKEN (secret)
#   - Optionally provide GITHUB_TOKEN and GITHUB_ACTOR if you want GH-specific login behavior
# - To run manually, choose parameters `runner` and `environment` in the Run pipeline dialog.
