# Azure Pipelines conversion of .github/workflows/build-EddictwareELEC-in-container.yml
# - Trigger: manual (workflow_dispatch equivalent)
# - Parameters mirror the GitHub Action inputs so you can run the pipeline interactively.
# Notes:
# - This pipeline expects pipeline variables/secrets to be provided for registry login:
#   - `GITHUB_ACTOR` (string)
#   - `GITHUB_TOKEN` (secret)
# - Consider replacing GHCR login with an Azure Container Registry service connection if you push to ACR.

trigger: none

pr: none

parameters:
  - name: runner
    displayName: Runner
    type: string
    default: github
    values:
      - github
      - self-hosted
  - name: os
    displayName: OS
    type: string
    default: noble
    values:
      - bookworm
      - jammy
      - noble
      - noble-custom
      - plucky
      - questing
      - sid
  - name: arch
    displayName: Arch
    type: string
    default: aarch64
    values:
      - amd64
      - aarch64
      - arm
      - x86_64

variables:
  EE_Distro: EddictwareELEC
  EE_Project: RPi
  EE_Device: RPi4
  # default registry used by the original workflow
  EE_Registry: ghcr.io
  BUILDKIT_PROGRESS: 'auto'
  # ACR service connection (use a service connection name to authenticate to ACR)
  ACR_SERVICE_CONNECTION: 'eddict-acr-connection'

jobs:
- job: init
  displayName: Init: compose builder image tag
  pool:
    ${{ if eq(parameters.runner, 'self-hosted') }}:
      name: 'Self-Hosted'
    ${{ if ne(parameters.runner, 'self-hosted') }}:
      vmImage: 'ubuntu-latest'
  steps:
  - bash: |
      echo "date=$(date -u +%Y%m%d)"
      echo "##vso[task.setvariable variable=build_date]$(date -u +%Y%m%d)"
    displayName: Get Date

  - bash: |
      DGUID=$(id -u docker 2>/dev/null || echo "0")
      echo "docker-guid=${DGUID}"
      echo "##vso[task.setvariable variable=docker_guid]${DGUID}"
    displayName: Get docker guid

  - bash: |
      # Compose image tag (lowercase)
      dTag="${EE_Registry}/eddict/${EE_Distro}-${{ parameters.os }}:latest"
      dTagLower=$(echo "${dTag}" | tr '[:upper:]' '[:lower:]')
      echo "EE_Distro_tag=${dTagLower}"
      echo "##vso[task.setvariable variable=EE_Distro_tag;isOutput=true]${dTagLower}"
    name: composeImage
    displayName: Compose image tag

- job: build
  displayName: Build image in container
  dependsOn: init
  pool:
    ${{ if eq(parameters.runner, 'self-hosted') }}:
      name: 'Self-Hosted'
    ${{ if ne(parameters.runner, 'self-hosted') }}:
      vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    displayName: Checkout repository
    persistCredentials: true
    clean: true

  - task: Docker@2
    displayName: Login to ACR (if ACR_SERVICE_CONNECTION set)
    inputs:
      containerRegistry: '$(ACR_SERVICE_CONNECTION)'
      command: login
    condition: ne(variables['ACR_SERVICE_CONNECTION'], '')

  - bash: |
      set -euo pipefail
      echo "## Compose values from init job"
      BUILDER_IMAGE="$(dependencies.init.outputs['composeImage.EE_Distro_tag'])"
      echo "Builder image: ${BUILDER_IMAGE}"
      # debug info
      echo "[pwd]: $PWD"
      echo "[NB_CORES]: $(nproc)"

      # login to registry (requires pipeline variables/secrets: GITHUB_ACTOR, GITHUB_TOKEN)
      if [ -n "${GITHUB_ACTOR:-}" ] && [ -n "${GITHUB_TOKEN:-}" ]; then
        docker login --username "${GITHUB_ACTOR}" --password "${GITHUB_TOKEN}" "${EE_Registry}"
      else
        echo "Warning: GITHUB_ACTOR or GITHUB_TOKEN not set; registry login skipped"
      fi

      docker --debug image pull "${BUILDER_IMAGE}"

      NB_CORES=$(grep -c '^processor' /proc/cpuinfo || echo 1)
      echo "[NB_CORES]: ${NB_CORES}"

      docker run --rm \
        --name "build${EE_Distro}.${{ parameters.os }}" \
        -v ${GITHUB_WORKSPACE}:/build \
        -w /build \
        -e DISABLE_COLORS=no \
        -e MTCOLORS=auto \
        -e ONELOG=no \
        -e LOGCOMBINE=fail \
        -e MTIMMEDIATE=no \
        -e MTDEBUG=no \
        -e MTVERBOSE=no \
        -e MTPROGRESS=no \
        -e DISTRO=${EE_Distro} \
        -e PROJECT=${EE_Project} \
        -e DEVICE=${EE_Device} \
        -e ARCH=${{ parameters.arch }} \
        -e BUILDER_NAME=Eddict \
        -e BUILDER_VERSION="13.0-$(date +%Y%m%d)" \
        "${BUILDER_IMAGE}" make -j$((NB_CORES+1)) -l${NB_CORES} image || true
    displayName: Build ${EE_Distro} image
    env:
      GITHUB_ACTOR: $(GITHUB_ACTOR)
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - bash: |
      # Copy built image to archive if present
      debug=true
      if [ -d "${GITHUB_WORKSPACE}/target" ]; then
        lines=$(find "${GITHUB_WORKSPACE}/target" -maxdepth 1 -type f -iname "${EE_Distro}-${EE_Device}.${{ parameters.arch }}*.img.gz" 2>/dev/null | wc -l)
        if [ "$lines" -ne 0 ]; then
          pathfilename=$(ls -t "${GITHUB_WORKSPACE}/target/${EE_Distro}-${EE_Device}.${{ parameters.arch }}*.img.gz" | head -n1)
          echo "EE_image_pathfilename=$pathfilename"
          filename="${pathfilename##*/}"
          echo "EE_image_filename=$filename"
          echo "##vso[task.setvariable variable=EE_image_pathfilename]${pathfilename}"
          echo "##vso[task.setvariable variable=EE_image_filename]${filename}"
          if [ ! -d /root/target_archive ]; then
            mkdir -p /root/target_archive
          fi
          cp -u "$pathfilename" /root/target_archive || true
        else
          echo "No built image found in target directory"
        fi
      else
        echo "No target directory found, skipping copy"
      fi
    displayName: Copy built image to archive

  - task: PublishPipelineArtifact@1
    displayName: Publish built image (if present)
    inputs:
      targetPath: '$(EE_image_pathfilename)'
      artifact: 'built_image'
      publishLocation: 'pipeline'
    condition: and(succeeded(), ne(variables['EE_image_pathfilename'], ''))

  - task: PublishPipelineArtifact@1
    displayName: Publish cache/artifacts
    inputs:
      targetPath: |
        $(GITHUB_WORKSPACE)/build.${EE_Distro}-${EE_Device}.${{ parameters.arch }}-13.0-devel/.cache_package_global
        $(GITHUB_WORKSPACE)/build.${EE_Distro}-${EE_Device}.${{ parameters.arch }}-13.0-devel/.ccache
        $(GITHUB_WORKSPACE)/build.${EE_Distro}-${EE_Device}.${{ parameters.arch }}-13.0-devel/.stamps
      artifact: 'build_cache'
      publishLocation: 'pipeline'
    condition: always()

# Usage notes:
# - Set pipeline variables (in pipeline UI or variable group):
#   - `GITHUB_ACTOR` (string) and `GITHUB_TOKEN` (secret) if you want to pull builder image from GHCR
# - Run pipeline manually and choose `runner`, `os`, and `arch` parameters.
