# https://dev.to/abiwinanda/github-action-adding-post-steps-in-composite-actions-5ak3
# https://github.com/pyTooling/Actions/blob/dev/with-post-step/action.yml
name: Delete workflow run
description: "Delete this workflow run"
runs:
  using: "composite"
  steps:
    - name: Delete workflow run
      uses: ./.github/actions/javascript/with-post-step
      with:
        key: INPOST # will be converted to capitals
        # Main command(s) executed by the action. Replace with appropriate shell or JS code.
        main: |
          echo "INPUT_POST: $INPUT_POST"
          echo "INPOST: $INPOST"

        # Post-step is an arbitrary JS snippet executed by the helper action — use a block scalar for readability.
        post: |
          echo "INPUT_POST from the main action: $INPUT_POST"
          echo "INPOST from the main action: $INPOST"

# console.log("INPUT_POST from the main action: " + process.env.INPUT_POST);
# console.log("INPOST from the main action: " + process.env.STATE_INPOST);
