# https://dev.to/abiwinanda/github-action-adding-post-steps-in-composite-actions-5ak3
# https://github.com/pyTooling/Actions/blob/dev/with-post-step/action.yml
name: Delete workflow run
description: "Delete this workflow run"
runs:
  using: "composite"
  steps:
    - name: Delete workflow run
      uses: ./.github/actions/javascript/with-post-step
      with:
        # Main command(s) executed by the action. Replace with appropriate shell or JS code.
        main: |
          # example: shell commands
          echo 'run main commands here'

        # Post-step is an arbitrary JS snippet executed by the helper action — use a block scalar for readability.
        post: |
          echo 'run post commands here'
        key: inPOST
