# https://dev.to/abiwinanda/github-action-adding-post-steps-in-composite-actions-5ak3
# https://github.com/pyTooling/Actions/blob/dev/with-post-step/action.yml
name: Delete workflow run
description: "Delete this workflow run"
runs:
  using: "composite"
  steps:
    - name: Delete workflow run
      uses: ./.github/actions/javascript/with-post-step
      with:
        # Run the helper action's main/post JS using node and a path relative to the action.
        # Using `node ./main.js` ensures the script is executed by Node and resolves from the action directory.
        main: 'node ./main.js'
        post: 'node ./post.js'
        key: INPOST # will be converted to capitals
