# https://dev.to/abiwinanda/github-action-adding-post-steps-in-composite-actions-5ak3
# https://github.com/pyTooling/Actions/blob/dev/with-post-step/action.yml
name: Delete workflow run
description: "Delete this workflow run"
runs:
  using: "composite"
  steps:
    - name: Install modules
      run: npm install @actions/core @actions/github

    - name: Delete workflow run
      uses: ./.github/actions/javascript/with-post-step
      with:
        main: 'main.js'
        post: 'post.js'
        key: INPOST # will be converted to capitals
