# https://dev.to/abiwinanda/github-action-adding-post-steps-in-composite-actions-5ak3
# https://github.com/pyTooling/Actions/blob/dev/with-post-step/action.yml
name: Delete workflow run
description: "Delete this workflow run"
runs:
  using: "composite"
  steps:
    - name: Install JS action dependencies
      run: |
        echo "Installing JS action dependencies for with-post-step"
        npm ci --prefix ./.github/actions/javascript/with-post-step
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Delete workflow run
      uses: ./.github/actions/javascript/with-post-step
      with:
        # Call the executable scripts directly; scripts include a shebang and are executable in git.
        main: './.github/actions/javascript/with-post-step/main.js'
        post: './.github/actions/javascript/with-post-step/post.js'
        key: INPOST # will be converted to capitals
