#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2016 Team LibreELEC (https://libreelec.tv)

if [ -z "$PROJECT" -a -z "$ARCH" ]; then
  echo "Usage: PROJECT=<project> ARCH=<arch> $0"
  exit 0
fi

help() {
  echo "Usage: PROJECT=<project> ARCH=<arch> $0 [-a|--all]"
  echo "Options:"
  echo "  -a, --all: download all packages including addons"
}

case $1 in
  -a | --all)
    ALL_PACKAGES="true"
    ;;
  -h | --help)
    help
    exit 0
    ;;
esac

# for package in $(find packages/ -name package.mk); do
#   if [ -n "$(echo $package | grep addons)" -a -z "$ALL_PACKAGES" ]; then
#     continue
#   fi
#   ./scripts/get $(basename $(dirname $package))
# done
# compute total (respecting ALL_PACKAGES)
if [ -z "${ALL_PACKAGES:-}" ]; then
  total=$(find packages/ -name package.mk | grep -v '/addons/' | wc -l)
else
  total=$(find packages/ -name package.mk | wc -l)
fi

i=0
find packages/ -name package.mk | while read -r pkgfile; do
  if [ -z "${ALL_PACKAGES:-}" ] && echo "$pkgfile" | grep -q '/addons/'; then
    continue
  fi
  i=$((i+1))
  pkg=$(basename "$(dirname "$pkgfile")")
  printf '[%d/%d] Downloading %s\n' "$i" "$total" "$pkg"
  ./scripts/get "$pkg"
done
