name: Yamllint Workflows

on:
  workflow_dispatch:
  push:
    paths: &yaml_files
      - '.github/**'

run-name: ${{ format('{0} ({1})', github.workflow, 'github') }}

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          # Disable cone mode to allow non-directory wildcards
          sparse-checkout-cone-mode: true
          clean: true
          fetch-depth: 1
          sparse-checkout: '.github'

      - name: Output PWD contents
        run: |
          echo "$PWD"
          ls -la
          ls -la .github

      - name: Run yamllint composite action
        uses: ./.github/actions/composite/yamllint
        # with:
        #   yamllint_files_or_dirs: '/.github/**'
        
      - name: Clean .git folder
        run: rm -rf .git 2>/dev/null || true
