name: Yamllint Workflows

on:
  workflow_dispatch:
  push:
    paths: &yaml_files |
      '/**/*.yml'
      '/**/*.yaml'

run-name: ${{ format('{0} ({1})', github.workflow, 'github') }}

jobs:
  yamllint:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          # Disable cone mode to allow non-directory wildcards
          sparse-checkout-cone-mode: false
          clean: false
          fetch-depth: 1
          #sparse-checkout: *yaml_files
          sparse-checkout: &yaml_files_str |
            '/**/*.yml'
            '/**/*.yaml'

      - name: Run yamllint composite action
        uses: ./.github/actions/composite/yamllint
        with:
          yamllint_files_or_dirs: *yaml_files_str
        
      - name: Clean .git folder
        run: rm -rf .git 2>/dev/null || true
